name: SonarCloud
on:
    pull_request:
        paths:
            - backend/src/**
            - backend/pom.xml
            - frontend/src/**
            - frontend/angular.json
        branches:
            - main
    workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Serve Angular in background
        run: npm run start:test &
          npx wait-on https://localhost:4200
        working-directory: ./frontend

      - name: Build and analyze
        working-directory: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.token=$SONAR_TOKEN \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=codeurjc-students \
              -Dsonar.projectKey=codeurjc-students_2025-PixelForum \
              -Dsonar.coverage.jacoco.xmlReportPaths=coverage/jacoco.xml